FROM 558467021483.dkr.ecr.ap-southeast-1.amazonaws.com/custom_ubuntu_py_base_image:1.0.0

# Defining some variables
RUN pip3 install --no-cache --upgrade \
    sagemaker-training

# Copies code under /opt/ml/code where sagemaker-containers expects to find the script to run
COPY py_app/criteo_ads_data/ /opt/ml/code/

# Defines train.py as script entry point
ENV SAGEMAKER_PROGRAM run_training.py
