FROM 763104351884.dkr.ecr.ap-southeast-1.amazonaws.com/tensorflow-training:2.3.1-cpu-py37-ubuntu18.04

# Defining some variables
RUN pip3 install --no-cache --upgrade \
    sagemaker-training

# Copies code under /opt/ml/code where sagemaker-containers expects to find the script to run
COPY py_app/criteo_ads_data/ /opt/ml/code/

# Defines train.py as script entry point
ENV SAGEMAKER_PROGRAM run_training.py
