name: Push tag CI

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy to testing env
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to AWS Deep learning container ECR
      id: login-aws-dlc
      uses: docker/login-action@v1
      with:
        registry: 763104351884.dkr.ecr.ap-southeast-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-aws-ecr-project
      uses: aws-actions/amazon-ecr-login@v1

    - name: CI - processing image to Amazon ECR
      id: build-image-prcossing
      env:
        ECR_REGISTRY: ${{ steps.login-aws-ecr-project.outputs.registry }}
        ECR_REPOSITORY: binary_classifier_lab
      run: |
        VERSION_TAG=${GITHUB_REF##*/}
        IMG_TAG="${VERSION_TAG}-PROCSSING"
        docker build -f Dockerfile.proc -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMG_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMG_TAG

    - name: CI - training image to Amazon ECR
      id: build-image-training
      env:
        ECR_REGISTRY: ${{ steps.login-aws-ecr-project.outputs.registry }}
        ECR_REPOSITORY: binary_classifier_lab
      run: |
        VERSION_TAG=${GITHUB_REF##*/}
        IMG_TAG="${VERSION_TAG}-TRAINING"
        docker build -f Dockerfile.train -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMG_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMG_TAG
